micronaut:
  application:
    name: linketinder
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/linketinder
    driverClassName: org.postgresql.Driver
    username: postgres
    password: Schloegl@20
    schema-generate: CREATE_DROP
    dialect: postgres
jpa:
  default:
    entity-scan:
      packages: 'Linketinder.src.main.groovy.Linketinder.utils'
